---
abstract: 'Attribute wrapper for Getopt::Long'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100711'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Getopt-Attribute
provides:
  Getopt::Attribute:
    file: lib/Getopt/Attribute.pm
    version: 1.100860
requires:
  Attribute::Handlers: 0
  Carp: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  Getopt::Long: 0
  Scalar::Util: 0
  Test::More: 0.88
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Getopt-Attribute
  homepage: http://search.cpan.org/dist/Getopt-Attribute/
  repository: http://github.com/hanekomu/Getopt-Attribute
version: 1.100860
