---
abstract: 'Attribute wrapper for Getopt::Long'
author:
  - 'Marcel GrE<uuml>nauer, C<< <marcel@cpan.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.70
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Getopt-Attribute
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  perl: 5.8.0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Getopt-Attribute
  homepage: http://search.cpan.org/dist/Getopt-Attribute/
  license: http://dev.perl.org/licenses/
  repository: git://github.com/hanekomu/getopt-attribute.git
version: 1.46
